name: 'Deploy Documentation to GitHub Pages'

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  doc-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby as asciidoctor Prerequisite
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install asciidoctor
        uses: reitzig/actions-asciidoctor@v2.0.0
        with:
          version: 2.0.10
      - name: Build Documentation Using Native Tool - asciidoctor
        run: |
          cd docs
          asciidoctor all_in_one.adoc
          mv all_in_one.html index.html
      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          user_name: QubitPi
          user_email: jack20191124@proton.me
